/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.wisc.lmcg.gui;

import static edu.wisc.lmcg.gui.MapGUI.getScalatedIcon;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dipaco
 */
public class OpenAlignmentDialog extends javax.swing.JDialog {
    
    private final String OPEN_ICON = "/edu/wisc/lmcg/resources/open.png";    
    private final String MOVE_UP_ICON = "/edu/wisc/lmcg/resources/move_up.png";
    private final String MOVE_DOWN_ICON = "/edu/wisc/lmcg/resources/move_down.png";
    private final int DEFAULT_BUTTON_SIZE = 16;

    /**
     * Creates new form NewJDialog
     */
    public OpenAlignmentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //btnOpen.setIcon(new ImageIcon(getScalatedIcon(OPEN_ICON, 16, DEFAULT_BUTTON_SIZE)));        
        btnMoveDown.setIcon(new ImageIcon(getScalatedIcon(MOVE_DOWN_ICON, DEFAULT_BUTTON_SIZE, DEFAULT_BUTTON_SIZE)));
        btnMoveUp.setIcon(new ImageIcon(getScalatedIcon(MOVE_UP_ICON, DEFAULT_BUTTON_SIZE, DEFAULT_BUTTON_SIZE)));
        
        /*this.listReferenceMaps.add("111");
        this.listReferenceMaps.add("112");
        this.listReferenceMaps.add("113");
        this.listReferenceMaps.add("114");*/
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                rb_referencemap.setSelected(true);
                dispose();
            }
        });
    }
    
    public void setReferenceMapNames(List<String> names){
        this.listReferenceMaps.removeAll();
        
        //Orders the elements in at least a natural way to improve the process
        //of selecting a new order
        names.sort((String f1, String f2) -> {
                        
            Matcher matcher1 = Pattern.compile("\\d+").matcher(f1);
            Matcher matcher2 = Pattern.compile("\\d+").matcher(f2);
            
            try{            
                matcher1.find();
                matcher2.find();


                int i1 = Integer.valueOf(matcher1.group());
                int i2 = Integer.valueOf(matcher2.group());

                if ( i1 > i2 )
                    return 1;
                else if ( i1 < i2 )
                    return -1;
                else            
                    return f1.compareTo(f2);
            }catch(Exception e){
                return f1.compareTo(f2);
            }
        });
        
        for ( String s : names){
            this.listReferenceMaps.add(s);
        }
    }
    
    public OrderMethod getOrderMethod(){
        if ( rb_custom_order.isSelected() ){
            return OrderMethod.CustomList;
        }else if ( rb_custom_order.isSelected() ){
            return OrderMethod.ReferenceMapName;
        }else{
            return OrderMethod.ReferenceMapName;
        }        
    }
    
    public LinkedList<String> getCustomList(){
        
        LinkedList<String> list = new LinkedList<>();
        for ( int i = 0; i < this.listReferenceMaps.getItemCount(); i++ ){
            list.add(this.listReferenceMaps.getItem(i));
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnMoveDown = new javax.swing.JButton();
        listReferenceMaps = new java.awt.List();
        rb_custom_order = new javax.swing.JRadioButton();
        rb_referencemap = new javax.swing.JRadioButton();
        btnOpen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMoveUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnMoveDown.setEnabled(false);
        btnMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveDownActionPerformed(evt);
            }
        });

        listReferenceMaps.setEnabled(false);

        buttonGroup1.add(rb_custom_order);
        rb_custom_order.setText("Custom order.");
        rb_custom_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_custom_orderActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_referencemap);
        rb_referencemap.setSelected(true);
        rb_referencemap.setText("Reference map size.");
        rb_referencemap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_referencemapActionPerformed(evt);
            }
        });

        btnOpen.setText("Open Alignment");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel2.setText("Select a method for ordering the alignmets:");

        btnMoveUp.setEnabled(false);
        btnMoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listReferenceMaps, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb_custom_order, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_referencemap, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMoveUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoveDown, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(rb_referencemap)
                .addGap(18, 18, 18)
                .addComponent(rb_custom_order)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoveUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoveDown)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(listReferenceMaps, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpen)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnMoveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveUpActionPerformed
        
        int sel_index = this.listReferenceMaps.getSelectedIndex();
        if ( sel_index > -1){
            String item = this.listReferenceMaps.getItem(sel_index);
            this.listReferenceMaps.remove(sel_index);
            sel_index = sel_index - 1 > -1 ? sel_index - 1 : 0;
            this.listReferenceMaps.add(item, sel_index);
            this.listReferenceMaps.select(sel_index);            
            this.listReferenceMaps.makeVisible(sel_index);
        }
        
    }//GEN-LAST:event_btnMoveUpActionPerformed

    private void btnMoveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveDownActionPerformed
        
        int sel_index = this.listReferenceMaps.getSelectedIndex();
        if ( sel_index > -1){
            String item = this.listReferenceMaps.getItem(sel_index);
            this.listReferenceMaps.remove(sel_index);
            sel_index = sel_index + 1 <= this.listReferenceMaps.getItemCount() ? sel_index + 1 : this.listReferenceMaps.getItemCount();
            this.listReferenceMaps.add(item, sel_index);
            this.listReferenceMaps.select(sel_index);
            this.listReferenceMaps.makeVisible(sel_index);
        }
    }//GEN-LAST:event_btnMoveDownActionPerformed

    private void rb_referencemapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_referencemapActionPerformed
        // TODO add your handling code here:
        if ( rb_referencemap.isSelected() ){
            this.setCustomOrderGUI(false);
        }
    }//GEN-LAST:event_rb_referencemapActionPerformed

    private void rb_custom_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_custom_orderActionPerformed
        // TODO add your handling code here:
        if ( rb_custom_order.isSelected() ){
            setCustomOrderGUI(true);
        }
    }//GEN-LAST:event_rb_custom_orderActionPerformed

    private void setCustomOrderGUI(boolean v){
        this.btnMoveUp.setEnabled(v);
            this.btnMoveDown.setEnabled(v);
            this.listReferenceMaps.setEnabled(v);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenAlignmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenAlignmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenAlignmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenAlignmentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OpenAlignmentDialog dialog = new OpenAlignmentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoveDown;
    private javax.swing.JButton btnMoveUp;
    private javax.swing.JButton btnOpen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List listReferenceMaps;
    private javax.swing.JRadioButton rb_custom_order;
    private javax.swing.JRadioButton rb_referencemap;
    // End of variables declaration//GEN-END:variables
}
